// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:game_on/data/models/hive/league_hive_model.dart';
import 'package:game_on/data/models/hive/league_player_hive_model.dart';
import 'package:game_on/data/models/hive/match_participant_hive_model.dart';
import 'package:game_on/data/models/hive/simple_match_hive_model.dart';
import 'package:game_on/data/models/hive/user_hive_model.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(LeagueHiveModelAdapter());
    registerAdapter(LeaguePlayerHiveModelAdapter());
    registerAdapter(MatchParticipantHiveModelAdapter());
    registerAdapter(SimpleMatchHiveModelAdapter());
    registerAdapter(UserHiveModelAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(LeagueHiveModelAdapter());
    registerAdapter(LeaguePlayerHiveModelAdapter());
    registerAdapter(MatchParticipantHiveModelAdapter());
    registerAdapter(SimpleMatchHiveModelAdapter());
    registerAdapter(UserHiveModelAdapter());
  }
}
